# Image containing Ubuntu 20.04, OpenMVG, OpenMVS, rust, cargo
FROM mamerillon/photogrammetry:20.04

# Install linux-tools for container Linux Kernel version: contains turbostat, perf scripts for measuring power consumption
RUN apt-get install -y linux-tools-$(uname -r)

# Add last camera database and export PATH for mvgmvs script
COPY ./sensor_width_camera_database.txt /usr/local/share/openMVG/
ENV PATH $PATH:/usr/local/share/openMVG

# Install pipeline
ADD MvgMvs_Pipeline.py /opt/
RUN chmod +x /opt/MvgMvs_Pipeline.py \
  && ln -s /opt/MvgMvs_Pipeline.py /usr/local/bin/mvgmvs

WORKDIR /root

# Prepare env
COPY ./run.sh /
RUN mkdir /data && mkdir /res && mkdir -p /logs/job && chmod a+x /run.sh
ENV DATA_DIR /data
ENV RES_DIR /res
ENV PHOTOGRAMMETRY_SCRIPT /run.sh

# Build webservice
COPY ./webservice /webservice

# Webservice dev environment installation and launch
RUN cd /webservice && cargo install cargo-watch

ENTRYPOINT cd /webservice && cargo watch -x run
