swagger: '2.0'
info:
  version: 1.0.0
  title: magnesie-photogrammetry
basePath: /api
schemes:
- http
paths:
  /job:
    post:
      summary: Launches a new job
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            photos:
              description: URLs of the photos that will be used for the 3D model
              type: array
              items:
                type: string
            callback:
              description: URL that sould be notified once the job is finished
              type: string
      responses:
        200:
          description: created successfully
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
        405:
          description: Invalid input
  /job/{id}:
    get:
      summary: Info on a current or past job
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: id of the requested job
        required: true
        type: integer
      responses:
        200:
          description: job description
          schema:
            type: object
            properties:
              status:
                type: string
                description: Current status of the requested job
              result:
                type: string
                description: If finished, url of the result